version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rustiscorm
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
  app:
    build: .
    env_file: .env
    depends_on: [db]
    ports: ["8081:8081"]
    volumes: ["./data:/app/data"]
volumes:
  pgdata:

